### ISSUE TITLE
Feature Request: do not force usage of ArtifactHUB

### ISSUE THREAD

**Issue by flavio** [kubewarden/go-policy-template#50]
### Is your feature request related to a problem?

Currently some make target will fail if there's not git tag specified, that's because this is required by the ArtifactHub integration we have.

However, some users might not even want to publish their policies on ArtifactHub

### Solution you'd like

Do not require ArtifactHub files to be created for doing "basic" tasks, like running the e2e tests. Have new dedicated targets

**Comment by fabriziosestito** [comment]
This happens at a random interval when the action runner triggers the `artifacthub-pkg.yml` Makefile target.
No tags are found since we do not fetch them in the checkout action, so the `git describe` command fails.

This does not happen when releasing, since in the release action we fetch tags, see: https://github.com/kubewarden/github-actions/blob/0b73198f5d655ef4ad84e423f8047044ed73fd4b/.github/workflows/reusable-release-policy-go.yml#L26

The issue started facing up when we added the e2e step to the [reusable-test-policy-go](https://github.com/kubewarden/github-actions/blob/main/.github/workflows/reusable-test-policy-go.yml) action

**This also happens when running the CI in a repository with no tags.**

One solution could be to add [`--always` ](https://git-scm.com/docs/git-describe#Documentation/git-describe.txt---always)to the `git describe` command so that if no tag is present the commit sha will be returned.

**Comment by flavio** [comment]
Thanks for the extra information. I would still prefer to implement the solution proposed in the issue description
